CREATE TABLE Rentalcar
(
   CARID     IDENTITY NOT NULL PRIMARY KEY,
   RENTALCAR_LOCATION    VARCHAR,
   CATEGORY    VARCHAR NOT NULL,
   COST        DECIMAL,
   MAKE        VARCHAR,
   MODEL       VARCHAR
);

 
